name: 'Setup SourcePawn Compiler'
author: 'rumblefrog'
description: 'Install and setup SourcePawn compiler'
inputs:
  version:
    description: 'Version of SP compiler'
    required: true
    default: '1.10.x'
outputs:
  version:
    description: 'Version of the SP compiler used'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'command'  
  color: 'blue'